Switched to bash_prompt_alt2

diff --git a/shell/bash_prompt b/shell/bash_prompt
--- a/shell/bash_prompt
+++ b/shell/bash_prompt
@@ -1,47 +1,54 @@
 #!/bin/bash
 
-# bash_prompt
+# bash_prompt_alt2
 
 echo "...~/.dotfiles/shell/bash_prompt loaded."
 
-if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ];
-then
-  # gitprompt configuration
-  # as per https://github.com/magicmonty/bash-git-prompt
-  # colors are defined by .prompt-colors.sh and .git-prompt-colors.sh
+# prompt from
+# http://www.terminally-incoherent.com/blog/2013/01/14/whats-in-your-bash-prompt/
 
-  # Set config variables first
+# set up command prompt
+function __prompt_command()
+{
+  # capture the exit status of the last command
 
-  # GIT_PROMPT_ONLY_IN_REPO=1
+  EXIT="$?"
+  PS1=""
+  if [ $EXIT -eq 0 ]; then PS1+="$Green[\!]$Color_Off "; else PS1+="$Red[\!]$Color_Off "; fi
 
-  GIT_PROMPT_SHOW_LAST_COMMAND_INDICATOR=1   # uncomment if you want to show
-                                             # the exit code of the last command
-                                             # in your prompt
-  GIT_PROMPT_FETCH_REMOTE_STATUS=0   # uncomment to avoid fetching remote status
+  # if logged in via ssh shows the ip of the client
+  if [ -n "$SSH_CLIENT" ]; then PS1+="$Yellow(${SSH_CLIENT%% *})$Color_Off"; fi
 
-  # GIT_PROMPT_START=...    # uncomment for custom prompt start sequence
-  # GIT_PROMPT_END=...      # uncomment for custom prompt end sequence
+  # debian chroot stuff (take it or leave it)
+  PS1+="${debian_chroot:+($debian_chroot)}"
 
-  # Now source the gitprompt script
-  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
-else
-  # Apple default terminal prompt from /private/etc/bashrc
+  # basic information (user@host:path)
+  PS1+="$BRed\u$Color_Off@$BRed\h$Color_Off:$BPurple\w$Color_Off "
 
-  PS1='\h:\W \u\$ '
-  # Make bash check its window size after a process completes
-  shopt -s checkwinsize
+  # check if inside git repo
+  local git_status="`git status -unormal 2>&1`"
+  if ! [[ "$git_status" =~ Not\ a\ git\ repo ]]; then
+    # parse the porcelain output of git status
+    if [[ "$git_status" =~ nothing\ to\ commit ]]; then
+      local Color_On=$Green
+    elif [[ "$git_status" =~ nothing\ added\ to\ commit\ but\ untracked\ files\ present ]]; then
+      local Color_On=$Purple
+    else
+      local Color_On=$Red
+    fi
+    if [[ "$git_status" =~ On\ branch\ ([^[:space:]]+) ]]; then
+      branch=${BASH_REMATCH[1]}
+    else
+      # Detached HEAD. (branch=HEAD is a faster alternative.)
+      branch="(`git describe --all --contains --abbrev=4 HEAD 2> /dev/null || echo HEAD`)"
+    fi
 
-  # Tell the terminal about the working directory at each prompt.
-  if [ "$TERM_PROGRAM" == "Apple_Terminal" ] && [ -z "$INSIDE_EMACS" ]; then
-      update_terminal_cwd() {
-          # Identify the directory using a "file:" scheme URL,
-          # including the host name to disambiguate local vs.
-          # remote connections. Percent-escape spaces.
-    local SEARCH=' '
-    local REPLACE='%20'
-    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
-    printf '\e]7;%s\a' "$PWD_URL"
-      }
-      PROMPT_COMMAND="update_terminal_cwd; $PROMPT_COMMAND"
+    # add the result to prompt
+    PS1+="$Color_On[$branch]$Color_Off "
   fi
-fi
+
+  # prompt $ or # for root
+  PS1+="\$ "
+}
+
+PROMPT_COMMAND=__prompt_command
