First Commit

diff --git a/shell/functions/datauri b/shell/functions/datauri
--- a/shell/functions/datauri
+++ b/shell/functions/datauri
@@ -8,3 +8,31 @@ datauri() {
     fi
     printf "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')" | pbcopy | printf "=> data URI copied to pasteboard.\n"
 }
+
+# Create an SSH key and uploads it to the given host
+# Based on https://gist.github.com/1761938
+ssh-add-host() {
+	username=$1
+	hostname=$2
+	identifier=$3
+
+	if [[ "$identifier" == "" ]] || [[ "$username" == "" ]] || [[ "$hostname" == "" ]]; then
+		echo "Usage: ssh-add-host <username> <hostname> <identifier>"
+	else
+		header "Generating key..."
+		if [ ! -f "$HOME/.ssh/$identifier.id_rsa" ]; then
+			ssh-keygen -f ~/.ssh/$identifier.id_rsa -C "$USER $(date +'%Y/%m%/%d %H:%M:%S')"
+		fi
+
+		if ! grep -Fxiq "host $identifier" "$HOME/.ssh/config"; then
+			echo -e "Host $identifier\n\tHostName $hostname\n\tUser $username\n\tIdentityFile ~/.ssh/$identifier.id_rsa" >> ~/.ssh/config
+		fi
+
+		header "Uploading key..."
+		ssh $identifier 'mkdir -p .ssh && cat >> ~/.ssh/authorized_keys' < ~/.ssh/$identifier.id_rsa.pub
+
+		tput bold; ssh -o PasswordAuthentication=no $identifier true && { tput setaf 2; echo "SSH key added."; } || { tput setaf 1; echo "Failure"; }; tput sgr0
+
+		_ssh_reload_autocomplete
+	fi
+}
